# Generated by Django 5.2.8 on 2025-12-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengaduan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pelaporan', models.DateField()),
                ('isi_laporan', models.TextField()),
                ('gambar_bukti', models.ImageField(blank=True, null=True, upload_to='bukti_laporan/')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
