# Generated by Django 5.2.8 on 2025-12-03 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_pengaduan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaduan',
            name='status',
            field=models.CharField(choices=[('menunggu', 'Menunggu'), ('proses', 'Dalam Proses'), ('selesai', 'Selesai')], default='menunggu', max_length=20),
        ),
        migrations.AddField(
            model_name='pengaduan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
