# Generated by Django 5.2.8 on 2025-12-04 02:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_pengaduan_status_pengaduan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Username ini sudah digunakan.'}, help_text='Wajib. 150 karakter atau kurang. Huruf, angka, dan spasi @/./+/-/_ saja.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(flags=0, message='Username hanya boleh mengandung huruf, angka, simbol (@/./+/-/_) dan spasi.', regex='^[\\w.@+\\- ]+$')]),
        ),
    ]
