# Generated by Django 5.2.8 on 2026-01-17 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLaporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesan', models.TextField()),
                ('file_pendukung', models.ImageField(blank=True, null=True, upload_to='chat_files/')),
                ('dikirim_pada', models.DateTimeField(auto_now_add=True)),
                ('pengaduan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='base.pengaduan')),
                ('pengirim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
